#!/usr/bin/env python

import pandas as pd
import numpy as np
import statistics as st
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

# Import data into memory
dataset = pd.read_csv("lung-cancer.data")

data_length = len(dataset)

X = dataset.iloc[:, :data_length].values
y = dataset.iloc[:, data_length].values

# Definindo vetores para guardar as informacoes para cada iteracao
Acertos_positivos = []
Acertos_negativos = []
Acertos_global = []
Numero_FP = []
Numero_FN = []

for i in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = i)
    sc = StandardScaler()
    print(dataset)
    X_train = sc.fit_transform(X_train)
    # Calculate W, the weight matrix.
    y_train[y_train == 0] = -1
    W = np.dot(np.linalg.pinv(X_train), y_train)
